### PR TITLE
Added a test suite

### PR DESCRIPTION
**Pull request by nwinkler**
To run the more than 600 tests, do the following:

* Install Node.js
* Run `npm install` in the project directory to install the test dependencies
* Run `npm test` to run the test suite. This will execute the 600+ unit tests for most of the replacements.

I also fixed a couple of issues in the existing replacements:

* Replacements now work in the middle of the sentence and at the end of a sentence.
* Avoiding false positives like "I use GitHub to work", where nothing should be replaced. I made a change so that in this case the description is not updated.
* Fixed upper case handling for "Windows XP" and "Windows Vista", where "XP" and "Vista" are corrected to use the correct case.

### CODE REVIEW

**Comment by nwinkler** [comment]
This should fix #55.

Once this is merged, you can enable automatic execution of the test suite on Travis-CI: https://travis-ci.org/AstroCB/Stack-Exchange-Editor-Toolkit

When that is done, I'll add another PR to add a Travis-CI badge on the project to show the test status.

**Comment by Unihedro** [comment]
Wrong links in package.json. Also would had appreciated atomic commits in groups, which makes it easier to review, but that's fine. Room for regex optimization too, but I don't think anyone would mind that.

**Comment by nwinkler** [comment]
Argh, sorry about that - I've fixed the links in `package.json` now.

I had originally split this up over 40+ commits, but there was no clean way to squash that into smaller groups, since the creation of the test suite and the fixes were intermingled.

I'm sure some of the regexes could be optimized, but that should be easier now with the test suite. When making changes, the test suite will be run and show any regression issues or breakages.

Can you enable the Travis build on the project? I've added a badge to the `README.md` to show the build status. https://travis-ci.org/AstroCB/Stack-Exchange-Editor-Toolkit

**Comment by AstroCB** [comment]
Great; thanks so much.

**Comment by nwinkler** [comment]
And a green build! https://travis-ci.org/AstroCB/Stack-Exchange-Editor-Toolkit/builds/79641564

**Pull request merged**
