### PR TITLE
Added replacement for various spellings of GitHub

### PR DESCRIPTION
**Pull request by nwinkler**
Regex test for this here: https://regex101.com/r/dA0fL9/1

### CODE REVIEW

**Comment by Unihedro** [comment]
If you replace the first group with a non-capturing group `(?:[gG]ithub|GITHUB)` Then there's one less capturing group and `$1` can be used instead. But precedence has shown against, so this can probably pass.

**Comment by nwinkler** [comment]
Thanks!

**Comment by Unihedro** [comment]
No, thank YOU.

**Comment by AstroCB** [comment]
Thanks!

**Comment by nwinkler** [comment]
You're welcome :-)

**Pull request merged**
